export const SET_FILM_CARDS = 'SET_FILM_CARDS';
export const LOAD_FILM_CARDS = 'LOAD_FILM_CARDS';
export const SET_SELECTED_FILM = 'SET_SELECTED_FILM';
export const LOAD_SELECTED_FILM = 'LOAD_SELECTED_FILM';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';